2020-01-02 19:49:26,905 [1] INFO  Microsoft.Hosting.Lifetime - Now listening on: http://localhost:5000
2020-01-02 19:49:26,917 [1] INFO  Microsoft.Hosting.Lifetime - Now listening on: http://localhost:5000
2020-01-02 19:49:26,923 [1] INFO  Microsoft.Hosting.Lifetime - Application started. Press Ctrl+C to shut down.
2020-01-02 19:49:26,928 [1] INFO  Microsoft.Hosting.Lifetime - Application started. Press Ctrl+C to shut down.
2020-01-02 19:49:26,933 [1] INFO  Microsoft.Hosting.Lifetime - Hosting environment: Development
2020-01-02 19:49:26,937 [1] INFO  Microsoft.Hosting.Lifetime - Hosting environment: Development
2020-01-02 19:49:26,944 [1] INFO  Microsoft.Hosting.Lifetime - Content root path: C:\Users\Administrator\Source\Repos\FineCoreIMS\FineCore.WebSite
2020-01-02 19:49:26,948 [1] INFO  Microsoft.Hosting.Lifetime - Content root path: C:\Users\Administrator\Source\Repos\FineCoreIMS\FineCore.WebSite
2020-01-02 19:49:28,495 [4] ERROR FineCore.WebSite.Controllers.HomeController - Hi, 这是Log4net日志。
2020-01-02 19:49:28,499 [4] ERROR FineCore.WebSite.Controllers.HomeController - Hi, 这是Log4net日志。
2020-01-02 19:49:28,592 [4] WARN  FineCore.WebSite.Controllers.HomeController - SQLSERVER
2020-01-02 19:49:28,597 [4] WARN  FineCore.WebSite.Controllers.HomeController - SQLSERVER
